// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pqkqzbkwguoktggszvus.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBxa3F6Ymt3Z3Vva3RnZ3N6dnVzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MjI2MDIsImV4cCI6MjA2NTQ5ODYwMn0.4H96DjAbtb3trCHcFOPxFyuxBkC-mtCvT7R5t6Gx_xk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);